# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_service_pb2 as chat__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiOrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.stream_stream(
                '/dateplanner.v1.AiOrchestrator/Chat',
                request_serializer=chat__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=chat__service__pb2.ChatDelta.FromString,
                _registered_method=True)
        self.KillChat = channel.unary_unary(
                '/dateplanner.v1.AiOrchestrator/KillChat',
                request_serializer=chat__service__pb2.KillChatRequest.SerializeToString,
                response_deserializer=chat__service__pb2.KillChatResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/dateplanner.v1.AiOrchestrator/GetChatHistory',
                request_serializer=chat__service__pb2.ChatHistoryRequest.SerializeToString,
                response_deserializer=chat__service__pb2.ChatHistoryResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/dateplanner.v1.AiOrchestrator/HealthCheck',
                request_serializer=chat__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=chat__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AiOrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request_iterator, context):
        """Bidirectional streaming: client sends one ChatRequest; server streams ChatDelta
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillChat(self, request, context):
        """Kill/terminate an active chat session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Get chat history for a session or user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=chat__service__pb2.ChatRequest.FromString,
                    response_serializer=chat__service__pb2.ChatDelta.SerializeToString,
            ),
            'KillChat': grpc.unary_unary_rpc_method_handler(
                    servicer.KillChat,
                    request_deserializer=chat__service__pb2.KillChatRequest.FromString,
                    response_serializer=chat__service__pb2.KillChatResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=chat__service__pb2.ChatHistoryRequest.FromString,
                    response_serializer=chat__service__pb2.ChatHistoryResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=chat__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=chat__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dateplanner.v1.AiOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dateplanner.v1.AiOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiOrchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dateplanner.v1.AiOrchestrator/Chat',
            chat__service__pb2.ChatRequest.SerializeToString,
            chat__service__pb2.ChatDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KillChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dateplanner.v1.AiOrchestrator/KillChat',
            chat__service__pb2.KillChatRequest.SerializeToString,
            chat__service__pb2.KillChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dateplanner.v1.AiOrchestrator/GetChatHistory',
            chat__service__pb2.ChatHistoryRequest.SerializeToString,
            chat__service__pb2.ChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dateplanner.v1.AiOrchestrator/HealthCheck',
            chat__service__pb2.HealthCheckRequest.SerializeToString,
            chat__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
